### ISSUE TITLE
[CI] Nuttx CI build using nuttx docker image

### ISSUE THREAD

**Issue by trns1997** [leducp/KickCAT#171]
I think we should consider testing build nuttx using https://github.com/apache/nuttx/pkgs/container/nuttx%2Fapache-nuttx-ci-linux docker image to automatically be up to date with nuttx master updates

**Comment by leducp** [comment]
Good idea

**Comment by trns1997** [comment]
I looked into this, it is not super straight forward, it seems we need to docker login to get access to ghcr (not completely sure yet) but the other problem is that the nuttx image does not have the nuttx-workspace setup, it simply has all different supported tool chains already setup and installed. Sooo the mechanism is not going to be very different sadly, we still need to somehow fetch nuttx sources and build using those. We could ask nuttx if it is possible for them to export a docker image with the sources already installed? And use that image as we do more of a build integration test.

**Comment by leducp** [comment]
Well, the current workflow works like a charm and I don't think it worth putting more effort into converting a working system into another one. I would rather prefer to put effort in the current Linux (and soon Windows) workflow to reduce its time by leveraging the cache system already in use in NuttX workflow.

On top of that, the current NuttX workflow is quite nice to just understand how to kickstart a NuttX build by just following it manually :)

**Comment by trns1997** [comment]
Agreed, the workflow perfectly mimics what a user needs to do to build a nuttx app using kickcat :)
