### ISSUE TITLE
Add the slave stack support

### ISSUE THREAD

**Issue by Rdk-T** [leducp/KickCAT#98]
Extend the project to provide a slave stack implementation.

**Comment by Rdk-T** [comment]
Tasks that will be addressed in further MR:

- Slave object: 
  - EEPROM handle at Slave level (access through EtherCAT registers)
  - Encapsulate call to read/write PDO in Slave (need to provide PDO address, data_in/out buffer size) -> slave config ?
  - Slave expose AL_STATUS, DL_STATUS, WDG status 
  - Check request from master if needed (on callback) if not in device emulation mode (may depends on eeprom config)

- Unit Tests  (Put the least intelligence in ESC to allow testing Slave with ESCMock)
- Example with simulator 
- spi class name due to arduino conflict -> shall resolve itself with spi injection in Lan92
- Manage code sharing between master and slave (Protocol.h, Errors.h ...) 
- timeout on the PDO R/W while waiting for fifo available ? specific lan92 ?

**Comment by leducp** [comment]
done, only unit test coverage is a bit low
